### ISSUE TITLE
Email issues

### ISSUE THREAD

**Issue by hugolundin** [teknik-eksjo/chronos#21]
I've made a working version of the email-login using tokens. But my problem is that when using the same configuration as in the flasky example for email (and a Gmail account) I get this error: 

``` python
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first
```

Is this a known issue? If someone would like to examine it, just comment so I can create a branch with my dummy functions for sending the email I've been using right now.

@Limpan

**Comment by Limpan** [comment]
Have you verified that the Flasky example works with the same settings?
http://stackoverflow.com/questions/34259004/flask-mail-error-smtpserverdisconnectedplease-run-connect-first Indicates that you might be out of favour with Gmail?

Check out [Sendgrid](https://sendgrid.com) or [Mailjet](https://www.mailjet.com) for transactional email services that probably is a better fit than Gmail for this application. There's usually a testing or dev mode that doesn't actually deliver the email but otherwise work the same.

**Comment by hugolundin** [comment]
When I ran the flasky-example with the same gmail-account it works without any problems. Will have to look and see if I have missed something in the configuration.

**Comment by hugolundin** [comment]
Do not ask me how I solved it, but now I get another error instead.. :)

``` python
  File "/Users/hugolundin/Code/git-repositories/chronos/venv/lib/python3.5/site-packages/flask_mail.py", line 351, in send
    connection.send(self)
  File "/Users/hugolundin/Code/git-repositories/chronos/venv/lib/python3.5/site-packages/flask_mail.py", line 168, in send
    message.as_string())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/smtplib.py", line 845, in sendmail
    msg = _fix_eols(msg).encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character '\xe4' in position 674: ordinal not in range(128)
```

**Comment by Limpan** [comment]
I think it's a Swedish åäö somewhere, possibly in a template or something like that. It's a typical message for code that expects English only ascii but receives Swedish ascii. Unicode/UTF-8 should be the answer.

**Comment by Limpan** [comment]
http://stackoverflow.com/questions/5910104/python-how-to-send-utf-8-e-mail
