### ISSUE TITLE
Create data model

### ISSUE THREAD

**Issue by Limpan** [teknik-eksjo/chronos#37]
Create a data model that supports teacher schedules (two parts, base and deviation) and periods.

**Comment by Greenheart** [comment]
@Limpan I'm interested in learning more about how to design the data model. Where should I start?

[This seems to be a good first resource](https://dev.mysql.com/tech-resources/articles/why-data-modeling.html) to get a feeling for the importance of this issue

**Comment by Limpan** [comment]
Start here: http://databasteknik.se/webbkursen/

I also have a written document about it, I'll see if I can post it on It's learning.

**Comment by Greenheart** [comment]
Thanks for the quick reply! I also found [this one](http://www.agiledata.org/essays/dataModeling101.html) which also look promising

**Comment by Greenheart** [comment]
I've read the basics about data modelling and started to think about
what chronos' data model could look like.

I will present my work so far in a few hours (my laptop battery died before
I could finish) to let the rest of you give feedback and suggestions :)

fredag 22 april 2016 skrev Linus Törngren <notifications@github.com>:

**Comment by Greenheart** [comment]
# A Suggestion for the Data Model

@teknik-eksjo/te13 Please come with feedback and suggestions. Could this be a good data model?
**Note:** There are some parts in the text below that discusses key functionality for the app. What do you think about my suggested solutions?

This basically means that a teacher need access to **their own row in the User-table**. However, they won't need much more since their user-row then gives them access to all their data where **some fields** in turn **link to rows in other tables**.

---

## DROP TABLE Users <-- 100% winrate

Here's my first try (ever) on data modeling with a relational DB:

### User
- firstname (string)
- lastname (string)
- email (string)
- last_seen (date)
- user_id (int or string?)
- password_hash (?)
- permissions
- work_periods (list of all work_periods **or only the most recent one**?)

### WorkPeriod
- owner_id (user_id of the owner)
- link to a `BaseSchedule`
- deviations (list of links to `Deviation`-entries for this period)
- description (string, added by the teacher to clarify how they are thinking)
- comment (string, added by the principal to give feedback on the teacher's sent in WorkPeriod)
- approved (boolean **or the userid** of the admin / principal who approved this schedule? --> If userId found in this field, schedule is approved and the teacherview / email notification to teacher could present _"Your WorkPeriod was approved by >Principal Name<"_. Else not approved and triggering similar response in UI / email)
- start_date (date)
- end_date (date)

### BaseSchedule

The `BaseSchedule` is a wrapper of several `Workday`s.
- monday (`Workday`)
- tuesday (`Workday`)
- wednesday (`Workday`)
- thursday (`Workday`)
- friday (`Workday`)

### Deviation

A `Deviation` is an exception from the `BaseSchedule` which adds a specific date
**Question:** Should a `Deviation` allow teachers to specify weekends as a `date`? There might be edge-cases where teachers work in weekends and thus this might be required?
- link to a `Workday`
- date (date)

### Workday
- start_time (int representing the start-time on the day **in minutes**, like the front-end probably will be?)
- lunch_start (int)
- lunch_end (int)
- end_time (int)

**Comment by Limpan** [comment]
Don't bother with views. The problem you try to solve with it shouldn't be solved in the database.

When it comes to the model I'll need to draw it out to see if it works.

**Comment by Greenheart** [comment]
@Limpan Seems reasonable to move it away from the DB. But we would still want some **general** way to limit different permission-levels to different parts of the DB? Because if we don't use views, wouldn't we have to add authentication code to every spot where users access data? - something that's much harder to implement and maintain.

Yes and we should probably use some kind of visual diagram to aid us in the discussions around the data model.

**Comment by Limpan** [comment]
Users don't access data, they view pages. It's you job as a programmer to limit what you send, that's why we have a few decorators relating to permissions (and the `can` method in User). Using views (or any other mechanism in the db layer) would only, at best, allow us to work with roles. That's not what we want as it's far too rigid and hard to maintain. Applying the permissions in our views (routes in Flask, mainly) will give us the flexibility we need.

Views in the db are for very complex queries and since we're using a good ORM (SQLAlchemy) we're highly unlikely to encounter a lot of those.

**Comment by Greenheart** [comment]
@teknik-eksjo/te13 This gives a better overview of how the different parts fit together. Any feedback? :)

![chronos-data-model-v1](https://cloud.githubusercontent.com/assets/6125097/14790669/83e2ac9c-0b12-11e6-9ef6-4e14efed0c32.jpg)

**Comment by Limpan** [comment]
There's a few issues.
1. You don't need to couple the deviation to the WorkPeriod.
2. Make the number of Workdays coupled to BaseSchedule flexible. Use an integer in Workday to create the order?
3. The WorkPeriods relation to BaseSchedule and User needs to be a three way one. Otherwise you won't know what User is connected to the BaseSchedule.

**Comment by Greenheart** [comment]
Here's the current version of the data model. 

Notable information:
- Comments will be a future feature
- `Deviation`s and `Workday`s are pretty similar. We'll use inheritance in `models.py` to let both deviations and workdays share the same python-code. However we won't worry about this initially, nor in the data model.

![13059382_1234402783251434_488465987_n](https://cloud.githubusercontent.com/assets/6125097/14811938/0e551990-0b9b-11e6-8a33-03174f55af6c.jpg)

**Comment by Limpan** [comment]
@Kallshem can help @Greenheart accomplish the model described in the latest comment.

**Comment by Greenheart** [comment]
## Progress
- [X] Create outline for classes in `models.py`
- [ ] Should we use time-`Interval`s or `Integer`s to store time?
- [ ] What data type should be used to store `Date`s?

### Implement methods for each class

#### Schedule
- [ ] `approve(schedule_id)` and `reject(schedule_id)` **or one method for both actions?**

#### WorkPeriod
- [ ] `update_time_span(work_period_id, start=None, end=None)`
  - Any passed `start`\- or `end`-values will be the new values of respectively property for the given `work_period`

#### Deviation

#### BaseSchedule

#### Workday

**Comment by Limpan** [comment]
You will probably not need that many helper functions but a few will probably end up as methods in the model. These will become apparent over time.

I'll close this for now and move the data type discussion to another issue.
